name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          override: true
          target: x86_64-pc-windows-msvc
          toolchain: stable

      - name: Package
        id: package
        env:
          TARGET: x86_64-pc-windows-msvc
          REF: ${{ github.ref }}
          OS: windows-latest
          TARGET_RUSTFLAGS: ""
        run: ./bin/package
        shell: bash

      - name: Publish Archive
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: ${{ steps.package.outputs.archive }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
